/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc.workshop_comp.add_new;

/**
 *
 * @author Rahil
 */
public class service extends javax.swing.JDialog {

    /**
     * Creates new form ad_ne_exp
     */
    public service(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_new_exp_dailog_panel = new javax.swing.JPanel();
        decription_label = new javax.swing.JLabel();
        jobcard = new javax.swing.JTextField();
        exp_amount = new javax.swing.JSpinner();
        exp_date = new org.jdesktop.swingx.JXDatePicker();
        service_type = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        exp_description = new javax.swing.JTextArea();
        submit_exp = new javax.swing.JButton();
        exp_cancel = new javax.swing.JButton();
        job_card_id_label = new javax.swing.JLabel();
        amount_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        service_type_label = new javax.swing.JLabel();
        custmer_name_label = new javax.swing.JLabel();
        tractor_hours = new javax.swing.JSpinner();
        village_label = new javax.swing.JLabel();
        taluka = new javax.swing.JComboBox();
        service_no_label = new javax.swing.JLabel();
        service_no = new javax.swing.JComboBox();
        village_label1 = new javax.swing.JLabel();
        village1 = new javax.swing.JComboBox();
        tractor_hours_label = new javax.swing.JLabel();
        cust_name1 = new javax.swing.JTextField();
        custmer_id_label2 = new javax.swing.JLabel();
        cust_id1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("new Service");

        add_new_exp_dailog_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decription_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decription_label.setText("Description:");
        add_new_exp_dailog_panel.add(decription_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 100, 30));

        jobcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobcardActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(jobcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 190, 30));

        exp_amount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_new_exp_dailog_panel.add(exp_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 650, 190, 30));
        add_new_exp_dailog_panel.add(exp_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 110, 30));

        service_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "workshop", "home", "service camp" }));
        service_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service_typeActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(service_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, 30));

        exp_description.setColumns(20);
        exp_description.setRows(5);
        jScrollPane1.setViewportView(exp_description);

        add_new_exp_dailog_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 310, 120));

        submit_exp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit_exp.setText("Submit");
        submit_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_expActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(submit_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 720, -1, -1));

        exp_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exp_cancel.setText("cancel");
        exp_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp_cancelActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(exp_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 720, -1, -1));

        job_card_id_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        job_card_id_label.setText("Jobcard No:");
        add_new_exp_dailog_panel.add(job_card_id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, 30));

        amount_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amount_label.setText("Total-Amount:");
        add_new_exp_dailog_panel.add(amount_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 120, 30));

        date_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date_label.setText("Date:");
        add_new_exp_dailog_panel.add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, 30));

        service_type_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        service_type_label.setText("Service Type:");
        add_new_exp_dailog_panel.add(service_type_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, 30));

        custmer_name_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        custmer_name_label.setText("Customer Name");
        add_new_exp_dailog_panel.add(custmer_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 30));
        add_new_exp_dailog_panel.add(tractor_hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 110, 30));

        village_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        village_label.setText("Taluka");
        add_new_exp_dailog_panel.add(village_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 120, 30));

        taluka.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "anand" }));
        taluka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talukaActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(taluka, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 180, 30));

        service_no_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        service_no_label.setText("Service Type:");
        add_new_exp_dailog_panel.add(service_no_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 120, 30));

        service_no.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1st service", "2st service", "3st service", "4st service", "5st service", "more than 5th service" }));
        service_no.setToolTipText("number of time service");
        add_new_exp_dailog_panel.add(service_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 180, 30));

        village_label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        village_label1.setText("Village");
        add_new_exp_dailog_panel.add(village_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 30));

        village1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "anand" }));
        village1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                village1ActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(village1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 180, 30));

        tractor_hours_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tractor_hours_label.setText("Tractor Hours");
        add_new_exp_dailog_panel.add(tractor_hours_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 110, 30));

        cust_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_name1ActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(cust_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 30));

        custmer_id_label2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        custmer_id_label2.setText("Customer ID:");
        add_new_exp_dailog_panel.add(custmer_id_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 110, 30));
        add_new_exp_dailog_panel.add(cust_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_new_exp_dailog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(add_new_exp_dailog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit_expActionPerformed

    private void exp_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exp_cancelActionPerformed

    private void jobcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobcardActionPerformed

    private void service_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_service_typeActionPerformed

    private void talukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talukaActionPerformed

    private void village1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_village1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_village1ActionPerformed

    private void cust_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_name1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                service dialog = new service(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_new_exp_dailog_panel;
    private javax.swing.JLabel amount_label;
    private javax.swing.JSpinner cust_id1;
    private javax.swing.JTextField cust_name1;
    private javax.swing.JLabel custmer_id_label2;
    private javax.swing.JLabel custmer_name_label;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel decription_label;
    private javax.swing.JSpinner exp_amount;
    private javax.swing.JButton exp_cancel;
    private org.jdesktop.swingx.JXDatePicker exp_date;
    private javax.swing.JTextArea exp_description;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel job_card_id_label;
    private javax.swing.JTextField jobcard;
    private javax.swing.JComboBox service_no;
    private javax.swing.JLabel service_no_label;
    private javax.swing.JComboBox service_type;
    private javax.swing.JLabel service_type_label;
    private javax.swing.JButton submit_exp;
    private javax.swing.JComboBox taluka;
    private javax.swing.JSpinner tractor_hours;
    private javax.swing.JLabel tractor_hours_label;
    private javax.swing.JComboBox village1;
    private javax.swing.JLabel village_label;
    private javax.swing.JLabel village_label1;
    // End of variables declaration//GEN-END:variables
}
