/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc.workshop_comp.add_new;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import ptc.workshop_comp.db_op;

/**
 *
 * @author Rahil
 */
public class stock_manage extends javax.swing.JDialog implements ChangeListener{

    /**
     * Creates new form expense
     */
    boolean sucess,insertvalid=true;
    String name,no,desc;
    int q,am;
    db_op op;
    public stock_manage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       total_amount.setEnabled(false);
       amount2.addChangeListener(this);
       qty.addChangeListener(this);
      // part_no.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_new_exp_dailog_panel = new javax.swing.JPanel();
        decription_label = new javax.swing.JLabel();
        part_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        exp_description = new javax.swing.JTextArea();
        submit_exp = new javax.swing.JButton();
        exp_cancel = new javax.swing.JButton();
        part_no_label = new javax.swing.JLabel();
        partt_name_label = new javax.swing.JLabel();
        qty_label = new javax.swing.JLabel();
        total_amount_label = new javax.swing.JLabel();
        part_no = new javax.swing.JTextField();
        qty = new javax.swing.JSpinner();
        amount_label1 = new javax.swing.JLabel();
        total_amount = new javax.swing.JSpinner();
        amount2 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("add new part");

        add_new_exp_dailog_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decription_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decription_label.setText("Description:");
        add_new_exp_dailog_panel.add(decription_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 100, 30));
        add_new_exp_dailog_panel.add(part_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 190, 30));

        exp_description.setColumns(20);
        exp_description.setRows(5);
        jScrollPane1.setViewportView(exp_description);

        add_new_exp_dailog_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 310, 120));

        submit_exp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit_exp.setText("Submit");
        submit_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_expActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(submit_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        exp_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exp_cancel.setText("cancel");
        exp_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exp_cancelActionPerformed(evt);
            }
        });
        add_new_exp_dailog_panel.add(exp_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, -1, -1));

        part_no_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        part_no_label.setText("Part No:");
        add_new_exp_dailog_panel.add(part_no_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 30));

        partt_name_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        partt_name_label.setText("Part Name:");
        add_new_exp_dailog_panel.add(partt_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, 30));

        qty_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qty_label.setText("Qty:");
        add_new_exp_dailog_panel.add(qty_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, 30));

        total_amount_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_amount_label.setText("Total Amount:");
        add_new_exp_dailog_panel.add(total_amount_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 120, 30));
        add_new_exp_dailog_panel.add(part_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 190, 30));

        qty.setModel(new javax.swing.SpinnerNumberModel());
        add_new_exp_dailog_panel.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 50, 30));

        amount_label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amount_label1.setText("Amount(MRP):");
        add_new_exp_dailog_panel.add(amount_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, 30));

        total_amount.setModel(new javax.swing.SpinnerNumberModel());
        add_new_exp_dailog_panel.add(total_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 110, 30));

        amount2.setModel(new javax.swing.SpinnerNumberModel());
        add_new_exp_dailog_panel.add(amount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_new_exp_dailog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add_new_exp_dailog_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_expActionPerformed
        // TODO add your handling code here:
         insertvalid=true;
         no=part_no.getText();
         name=part_name.getText();
         am=(Integer)amount2.getValue();
         q=(Integer)qty.getValue();
         desc=exp_description.getText();
         
       if(no.trim().length()==0 ){popup("please enter valid part no!!","error","error");insertvalid=false;}
       if(name.trim().length()==0){popup("please enter valid part name!!","error","error");insertvalid=false;}
       if(am<=0 || q<=0){popup("please enter valid  qty and amount!!","error","error");insertvalid=false;}  
       if(insertvalid)
        {
           
        try {
            String insert="part_no=\'"+no+"\',part_name=\'"+name+"\',qty=\'"+q+"\',amount=\'"+am+"\',total_amount=\'"+(Integer)total_amount.getValue()+"\'";
            op=new db_op();
           sucess= op.setdata("stock_workshop",insert);
          if(sucess)
          {
           popup("SUCESSFULLY ADDED!!!","sucess","sucess");
           dispose();
          }
          else{popup("error: please fill all required detail!!","","error");}
         
        } catch (Exception ex) {
            popup("error: in sql query !!"+ex.toString(),null,"error");
        }
        }
    }//GEN-LAST:event_submit_expActionPerformed

    private void exp_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exp_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exp_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stock_manage dialog = new stock_manage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void popup(String msg,String title,String type)
  {
     
      if(type.equalsIgnoreCase("error"))
      {
          //System.out.println("error");
      JOptionPane.showMessageDialog(this,msg,title,JOptionPane.ERROR_MESSAGE);
      }    
      if(type.equalsIgnoreCase("sucess"))
      {
         // System.out.print("sucess");
      JOptionPane.showMessageDialog(null,msg,title,JOptionPane.INFORMATION_MESSAGE);
      }
  
  }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add_new_exp_dailog_panel;
    private javax.swing.JSpinner amount2;
    private javax.swing.JLabel amount_label1;
    private javax.swing.JLabel decription_label;
    private javax.swing.JButton exp_cancel;
    private javax.swing.JTextArea exp_description;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField part_name;
    private javax.swing.JTextField part_no;
    private javax.swing.JLabel part_no_label;
    private javax.swing.JLabel partt_name_label;
    private javax.swing.JSpinner qty;
    private javax.swing.JLabel qty_label;
    private javax.swing.JButton submit_exp;
    private javax.swing.JSpinner total_amount;
    private javax.swing.JLabel total_amount_label;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public void stateChanged(ChangeEvent e) {
         am=(Integer)amount2.getValue();
         q=(Integer)qty.getValue();
        total_amount.setValue(new Integer(am*q));
    }

   

    
}
