/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc.workshop_comp;

import ptc.workshop_comp.add_new.expense;
import com.xzq.osc.field.DateValuePicker;
import java.awt.print.PrinterException;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.ComponentUI;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.JXMonthView;
import org.jdesktop.swingx.plaf.DatePickerUI;
import ptc.workshop;


/**
 *
 * @author Rahil
 */
public class main_expense extends javax.swing.JPanel {

    /**
     * Creates new form main_expense
     */
    expense  addnew_exp_dailog;
    ResultSet getdata;
    db_op op;
    public main_expense() throws ClassNotFoundException, SQLException {
        initComponents();
        setVisible(true);
        /* set format of datepciker text box */
        from_date.setFormats("dd-M-yyyy");
        to_date.setFormats("dd-M-yyyy");
        refreshdata();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        testDayPicker1 = new com.qt.datapicker.TestDayPicker();
        testDayPicker2 = new com.qt.datapicker.TestDayPicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        record_table = new javax.swing.JTable();
        search_panel1 = new javax.swing.JPanel();
        viewby_label = new javax.swing.JLabel();
        from_date = new org.jdesktop.swingx.JXDatePicker();
        to_label = new javax.swing.JLabel();
        to_date = new org.jdesktop.swingx.JXDatePicker();
        search_button = new javax.swing.JButton();
        excel = new javax.swing.JLabel();
        pdf = new javax.swing.JLabel();
        add_new_button = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        summary = new javax.swing.JPanel();
        no_exp_label = new javax.swing.JLabel();
        total_exp_label = new javax.swing.JLabel();
        no_expense_item = new javax.swing.JLabel();
        total_exp = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));

        record_table.setAutoCreateRowSorter(true);
        record_table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        record_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Index", "Name", "Amount", "Date", "Description", "Expense-Type", "Edit", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        record_table.setToolTipText("total expenses detail");
        record_table.setCellSelectionEnabled(true);
        record_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        record_table.setEnabled(false);
        record_table.setFocusable(false);
        record_table.setGridColor(new java.awt.Color(45, 56, 97));
        record_table.setRequestFocusEnabled(false);
        record_table.setRowHeight(25);
        record_table.setRowSorter(null);
        record_table.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(record_table);
        record_table.getColumnModel().getColumn(0).setPreferredWidth(30);

        viewby_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewby_label.setText("from:");

        to_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        to_label.setText("to:");

        search_button.setText("search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        excel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rahil\\Documents\\NetBeansProjects\\JavaApplication1\\src\\logo\\excel.png")); // NOI18N

        pdf.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rahil\\Documents\\NetBeansProjects\\JavaApplication1\\src\\logo\\pdf-file-32.png")); // NOI18N
        pdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdfMouseClicked(evt);
            }
        });

        add_new_button.setText("add new");
        add_new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_buttonActionPerformed(evt);
            }
        });

        refresh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_panel1Layout = new javax.swing.GroupLayout(search_panel1);
        search_panel1.setLayout(search_panel1Layout);
        search_panel1Layout.setHorizontalGroup(
            search_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewby_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(from_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(to_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(to_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(add_new_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(excel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdf)
                .addGap(12, 12, 12))
        );
        search_panel1Layout.setVerticalGroup(
            search_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(to_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewby_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(from_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(to_date, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_new_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(search_panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(242, 249, 248));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        no_exp_label.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        no_exp_label.setText("Total Item:");

        total_exp_label.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        total_exp_label.setText("Total-Expense:");

        no_expense_item.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        total_exp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout summaryLayout = new javax.swing.GroupLayout(summary);
        summary.setLayout(summaryLayout);
        summaryLayout.setHorizontalGroup(
            summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(total_exp_label, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(no_exp_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_expense_item, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(total_exp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        summaryLayout.setVerticalGroup(
            summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(no_exp_label, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(no_expense_item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(summaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_exp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(summary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        try
        {
            SimpleDateFormat mdyFormat = new SimpleDateFormat("yyyy-M-dd");
            String from_dat = mdyFormat.format(from_date.getDate());
            String to_dat = mdyFormat.format(to_date.getDate());
            try {
                op = new db_op();
                getdata=op.getdatasearch("expense_workshop",from_dat,to_dat);
                record_table.setModel(DbUtils.resultSetToTableModel(getdata));
                summary();
                if(!tablecheck()){refreshdata();}
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        catch(NullPointerException ex)
        {
             JOptionPane.showMessageDialog(null, "please enter valid to and from date!!!","error",JOptionPane.ERROR_MESSAGE);
            try {
                
            } catch (Exception ex1) {
                JOptionPane.showMessageDialog(null, "please enter valid text!!!"+ex1.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
                 try {
                     refreshdata();
                 } catch (ClassNotFoundException ex2) {
                     Logger.getLogger(main_expense.class.getName()).log(Level.SEVERE, null, ex2);
                 } catch (SQLException ex2) {
                     Logger.getLogger(main_expense.class.getName()).log(Level.SEVERE, null, ex2);
                 }
            } 
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void add_new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_buttonActionPerformed
        // TODO add your handling code here:
        addnew_exp_dailog=new expense(new javax.swing.JFrame(), true);
        addnew_exp_dailog.setAlwaysOnTop(true);
        addnew_exp_dailog.setVisible(true);
        try {
            refreshdata();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main_expense.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(main_expense.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_new_buttonActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        try {
            // TODO add your handling code here:
            refreshdata();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main_expense.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(main_expense.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refreshActionPerformed

    private void pdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfMouseClicked
        try {
            record_table.print();
           
        } catch (PrinterException ex) {
            Logger.getLogger(main_expense.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pdfMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_button;
    private javax.swing.JLabel excel;
    private org.jdesktop.swingx.JXDatePicker from_date;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel no_exp_label;
    private javax.swing.JLabel no_expense_item;
    private javax.swing.JLabel pdf;
    private javax.swing.JTable record_table;
    private javax.swing.JButton refresh;
    private javax.swing.JButton search_button;
    private javax.swing.JPanel search_panel1;
    private javax.swing.JPanel summary;
    private com.qt.datapicker.TestDayPicker testDayPicker1;
    private com.qt.datapicker.TestDayPicker testDayPicker2;
    private org.jdesktop.swingx.JXDatePicker to_date;
    private javax.swing.JLabel to_label;
    private javax.swing.JLabel total_exp;
    private javax.swing.JLabel total_exp_label;
    private javax.swing.JLabel viewby_label;
    // End of variables declaration//GEN-END:variables

public static void main(String args[]) throws ClassNotFoundException, SQLException
{
new main_expense();
}
public void refreshdata() throws ClassNotFoundException, SQLException
{
        db_op op=new db_op();
        getdata=op.getData("expense_workshop");
        record_table.setModel(DbUtils.resultSetToTableModel(getdata));
        summary();
}
 public boolean tablecheck() 
    {
    if(record_table.getRowCount()<1){
           JOptionPane.showMessageDialog(null,"no record found!!!");
           return false;
        }
    return true;
    }
 public void summary()
 {
     int total_item=record_table.getRowCount();
     int total=0;
     for (int i = 0;  i < total_item; i++) 
        { 
            total=total+Integer.parseInt(record_table.getValueAt(i,3).toString()); 
            System.out.print(record_table.getValueAt(i,3));
        }
     no_expense_item.setText(Integer.toString(total_item));
     total_exp.setText(Integer.toString(total));
     
 }
}
