/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc.workshop_comp;

import ptc.workshop_comp.add_new.expense;
import com.xzq.osc.field.DateValuePicker;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.JXMonthView;
import org.jdesktop.swingx.plaf.DatePickerUI;
import ptc.workshop;
import ptc.workshop_comp.add_new.stock_manage;


/**
 *
 * @author Rahil
 */
public class stock_management extends javax.swing.JPanel {

    /**
     * Creates new form main_expense
     */
    stock_manage  addnew_stock_dailog;
    ResultSet getdata;
    db_op op;
    boolean searchvalid=true;
    public stock_management() throws ClassNotFoundException, SQLException {
        initComponents();
        setVisible(true);
        /* set format of datepciker text box */
       
        refreshdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        testDayPicker1 = new com.qt.datapicker.TestDayPicker();
        testDayPicker2 = new com.qt.datapicker.TestDayPicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        record_table = new javax.swing.JTable();
        search_panel1 = new javax.swing.JPanel();
        search_button = new javax.swing.JButton();
        excel = new javax.swing.JLabel();
        pdf = new javax.swing.JLabel();
        add_new_button = new javax.swing.JButton();
        search_txt = new javax.swing.JTextField();
        refresh_button = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setBackground(new java.awt.Color(255, 255, 255));

        record_table.setAutoCreateRowSorter(true);
        record_table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        record_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "part no", "Part Name", "Qty", "amount", "total amount", "Edit", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        record_table.setToolTipText("total stock detail");
        record_table.setEnabled(false);
        record_table.setRowHeight(25);
        record_table.setRowSelectionAllowed(false);
        record_table.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(record_table);
        record_table.getColumnModel().getColumn(0).setPreferredWidth(30);

        search_button.setText("search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        excel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rahil\\Documents\\NetBeansProjects\\JavaApplication1\\src\\logo\\excel.png")); // NOI18N

        pdf.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rahil\\Documents\\NetBeansProjects\\JavaApplication1\\src\\logo\\pdf-file-32.png")); // NOI18N

        add_new_button.setText("add new");
        add_new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_buttonActionPerformed(evt);
            }
        });

        search_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        refresh_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        refresh_button.setText("Refresh");
        refresh_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_panel1Layout = new javax.swing.GroupLayout(search_panel1);
        search_panel1.setLayout(search_panel1Layout);
        search_panel1Layout.setHorizontalGroup(
            search_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(add_new_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(refresh_button, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                .addComponent(excel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdf)
                .addGap(12, 12, 12))
        );
        search_panel1Layout.setVerticalGroup(
            search_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(excel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_new_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_txt)
                    .addGroup(search_panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refresh_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addGap(236, 236, 236))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_buttonActionPerformed
        // TODO add your handling code here:
        addnew_stock_dailog=new stock_manage(new javax.swing.JFrame(), true);
        addnew_stock_dailog.setAlwaysOnTop(true);
        addnew_stock_dailog.setVisible(true);
        try {
            refreshdata();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_new_buttonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        searchvalid=true;
        if(search_txt.getText().trim().length()==0)
        {
            JOptionPane.showMessageDialog(null, "please enter valid text!!!","error",JOptionPane.ERROR_MESSAGE);
            searchvalid=false;
            try {
                refreshdata();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(searchvalid)
        {
            String search_text=search_txt.getText();

            try {
                op = new db_op();
                getdata=op.getdatasearch("stock_workshop",search_text);
                record_table.setModel(DbUtils.resultSetToTableModel(getdata));
                if(!tablecheck()){refreshdata();}
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_search_buttonActionPerformed

    private void refresh_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_buttonActionPerformed
        try {
            // TODO add your handling code here:
            refreshdata();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_refresh_buttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_button;
    private javax.swing.JLabel excel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pdf;
    private javax.swing.JTable record_table;
    private javax.swing.JButton refresh_button;
    private javax.swing.JButton search_button;
    private javax.swing.JPanel search_panel1;
    private javax.swing.JTextField search_txt;
    private com.qt.datapicker.TestDayPicker testDayPicker1;
    private com.qt.datapicker.TestDayPicker testDayPicker2;
    // End of variables declaration//GEN-END:variables

public static void main(String args[])
{
        try {
            new stock_management();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(stock_management.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void refreshdata() throws ClassNotFoundException, SQLException
{
        db_op op=new db_op();
        getdata=op.getData("stock_workshop");
        record_table.setModel(DbUtils.resultSetToTableModel(getdata));
       //tablecheck();
}
        public boolean tablecheck() 
    {
    if(record_table.getRowCount()<1){
           JOptionPane.showMessageDialog(null,"no record found!!!");
           return false;
        }
    return true;
    }
        
 }
