/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc;

import java.awt.Dimension;

/**
 *
 * @author Rahil
 */
public class footer extends javax.swing.JPanel {

    /**
     * Creates new form footer
     */
    public footer() {
        initComponents();
       footer_label.setText("<html>copyright &copy; 2013 <b>Patel Tractor Corporation Private Limited</b> all rights reserved.</html>");
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footer_label = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        footer_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        footer_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        footer_label.setText("copyright: 2013 all right reserved by patel tractor corporation private limited");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(footer_label)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(footer_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer_label;
    // End of variables declaration//GEN-END:variables
}
