/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ptc;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ptc.workshop_comp.header;
import ptc.workshop_comp.main_expense;
import ptc.workshop_comp.main_profit;
import ptc.workshop_comp.services;
import ptc.workshop_comp.stock_management;

/**
 *
 * @author Rahil
 */
public class workshop extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form workshop
     */
    header h;
    main_expense middle;
    main_profit middle1;
    stock_management middle2;
    services middle3;
    footer f;
  
    public workshop() throws ClassNotFoundException, SQLException {
        initComponents();
        setExtendedState(workshop.MAXIMIZED_BOTH);
        pack();
        //h=new header();
        middle=new main_expense();
        middle1=new main_profit();
        middle2=new stock_management();
        middle3=new services();
        
        f=new footer();
        //add(h,java.awt.BorderLayout.NORTH);
        add(f,java.awt.BorderLayout.SOUTH);
        add(middle);
        expense_button.addActionListener(this);
        stock_button.addActionListener(this);
        service_button.addActionListener(this);
        logout.addActionListener(this);
        modulebox.addActionListener(this);
        profit.addActionListener(this);
    
    }
 

    
    

    
    
    
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        expense_button = new javax.swing.JButton();
        service_button = new javax.swing.JButton();
        stock_button = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        modulebox = new javax.swing.JComboBox();
        profit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("welcome to ptc workshop");

        jPanel1.setBackground(new java.awt.Color(75, 109, 208));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 100));

        expense_button.setText("Expense");
        expense_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expense_buttonActionPerformed(evt);
            }
        });

        service_button.setText("service");
        service_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                service_buttonActionPerformed(evt);
            }
        });

        stock_button.setText("Stock Management");
        stock_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_buttonActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rahil\\Documents\\NetBeansProjects\\JavaApplication1\\src\\logo\\exit.png")); // NOI18N
        logout.setActionCommand("logout");

        modulebox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "workshop", "office" }));
        modulebox.setActionCommand("moduleChanged");
        modulebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleboxActionPerformed(evt);
            }
        });

        profit.setText("Profit");
        profit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expense_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stock_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(service_button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(modulebox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(expense_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulebox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stock_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(service_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moduleboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moduleboxActionPerformed

    private void stock_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_buttonActionPerformed
        // TODO add your handling code here:
         remove(middle);
        remove(middle1);
        remove(middle3);
        
        add(middle2).setVisible(true);
        validate();
         repaint();
    }//GEN-LAST:event_stock_buttonActionPerformed

    private void expense_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expense_buttonActionPerformed
        // TODO add your handling code here:
         remove(middle1);
        remove(middle2);
        remove(middle3);
        add(middle).setVisible(true);
        validate();
        repaint();
    }//GEN-LAST:event_expense_buttonActionPerformed

    private void service_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_service_buttonActionPerformed
        // TODO add your handling code here:
        
        remove(middle);
        remove(middle1);
        remove(middle2);
        add(middle3).setVisible(true);
        validate();
        repaint();
    }//GEN-LAST:event_service_buttonActionPerformed

    private void profitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitActionPerformed
        // TODO add your handling code here:
        remove(middle);
        remove(middle2);
        remove(middle3);
        add(middle1).setVisible(true);
        validate();
        repaint();
    }//GEN-LAST:event_profitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new workshop().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(workshop.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(workshop.class.getName()).log(Level.SEVERE, null, ex);
                }
           
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton expense_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox modulebox;
    private javax.swing.JButton profit;
    private javax.swing.JButton service_button;
    private javax.swing.JButton stock_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     /*  
    if(e.getActionCommand()=="stock management")
        {
            System.out.println(e.getActionCommand().toString());
        remove(middle);
        remove(middle1);
        remove(middle3);
        
        add(middle2).setVisible(true);
        validate();
         repaint();
        }
    if(e.getActionCommand()=="expense")
        {
            System.out.println(e.getActionCommand().toString());
        remove(middle1);
        remove(middle2);
        remove(middle3);
        add(middle).setVisible(true);
        validate();
        repaint();
        }
    if(e.getActionCommand()=="profit")
        {
            System.out.println(e.getActionCommand().toString());
        remove(middle);
        remove(middle2);
        remove(middle3);
        add(middle1).setVisible(true);
        validate();
        repaint();
        }
    if(e.getActionCommand()=="service")
        {
            System.out.println(e.getActionCommand().toString());
        remove(middle);
        remove(middle1);
        remove(middle2);
        add(middle3).setVisible(true);
        validate();
        repaint();
        
        }*/
    //System.out.print(e.getActionCommand());
     if(e.getActionCommand()=="logout")
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "ARE YOU SURE??", "LOGOUT",dialogButton);
            if(dialogResult==0)
            {
                //System.out.println("Yes option");
                try {
                    new Login().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(workshop.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(workshop.class.getName()).log(Level.SEVERE, null, ex);
                }
                    
                dispose();

            }
        
        }
     if(e.getSource()==modulebox)
     {
          String module_name=modulebox.getSelectedItem().toString();
          int selectedIndex = modulebox.getSelectedIndex();
         // System.out.print(selectedIndex);
        if(module_name=="office")
        {
           int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "ARE YOU SURE??", "change module?",dialogButton);
            if(dialogResult==0)
            {
                //System.out.println("Yes option");
                new office().setVisible(true);
                dispose();
            }
            else
            {            
               modulebox.setSelectedIndex(0);
            }
        }
     }
     
   }//action perform method end here

   

}//class end here